name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLOUD_MONGO_STRING: ${{ secrets.CLOUD_MONGO_STRING }}
      ABC: ${{ secrets.ABC }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check secrets
      run: echo ${{ env.CLOUD_MONGO_STRING }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    
    

    - name: Install Dependencies
      run: npm install
    
    - name: Run test
      run: npm test